"""add spot_reviews table and rating cache to spots

Revision ID: 4e7b6580fd0f
Revises: 24da437524a4
Create Date: 2026-04-18 17:43:43.634933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7b6580fd0f'
down_revision: Union[str, None] = '24da437524a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('spot_uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_review_rating_range'),
    sa.ForeignKeyConstraint(['spot_uid'], ['spots.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('spot_uid', 'user_id', name='uq_spot_user_review')
    )
    op.create_index(op.f('ix_spot_reviews_spot_uid'), 'spot_reviews', ['spot_uid'], unique=False)
    op.create_index(op.f('ix_spot_reviews_user_id'), 'spot_reviews', ['user_id'], unique=False)
    op.add_column('spots', sa.Column('rating_avg', sa.Float(), nullable=False))
    op.add_column('spots', sa.Column('review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'review_count')
    op.drop_column('spots', 'rating_avg')
    op.drop_index(op.f('ix_spot_reviews_user_id'), table_name='spot_reviews')
    op.drop_index(op.f('ix_spot_reviews_spot_uid'), table_name='spot_reviews')
    op.drop_table('spot_reviews')
    # ### end Alembic commands ###
