"""create initial tables

Revision ID: d3c40504a639
Revises:
Create Date: 2026-04-16 23:11:59.661493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3c40504a639"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camping_spots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("amenities", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_camping_spots_name"), "camping_spots", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_camping_spots_region"), "camping_spots", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_camping_spots_status"), "camping_spots", ["status"], unique=False
    )
    op.create_table(
        "spot_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("amenities", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("reporter_contact", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("spot_reports")
    op.drop_index(op.f("ix_camping_spots_status"), table_name="camping_spots")
    op.drop_index(op.f("ix_camping_spots_region"), table_name="camping_spots")
    op.drop_index(op.f("ix_camping_spots_name"), table_name="camping_spots")
    op.drop_table("camping_spots")
    # ### end Alembic commands ###
