"""add gocamping fields to spots

Revision ID: e97562523958
Revises: 4e7b6580fd0f
Create Date: 2026-04-19 14:55:11.986096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e97562523958"
down_revision: Union[str, None] = "4e7b6580fd0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spots", sa.Column("website_url", sa.String(), nullable=True))
    op.add_column("spots", sa.Column("booking_url", sa.String(), nullable=True))
    op.add_column("spots", sa.Column("features", sa.String(), nullable=True))
    op.add_column(
        "spots", sa.Column("category", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("spots", sa.Column("total_area_m2", sa.Float(), nullable=True))
    op.add_column(
        "spots", sa.Column("has_liability_insurance", sa.Boolean(), nullable=True)
    )
    op.create_index(op.f("ix_spots_rating_avg"), "spots", ["rating_avg"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spots_rating_avg"), table_name="spots")
    op.drop_column("spots", "has_liability_insurance")
    op.drop_column("spots", "total_area_m2")
    op.drop_column("spots", "category")
    op.drop_column("spots", "features")
    op.drop_column("spots", "booking_url")
    op.drop_column("spots", "website_url")
    # ### end Alembic commands ###
